version: "3.7"

services:
  backend:
    container_name: totvs-backend
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    container_name: totvs-mongo
    ports:
      - "27017:27017"

  mongo-seed:
    container_name: totvs-mongo-seed
    build: ./mongo-seed
    depends_on:
      - mongo

  frontend:
    container_name: totvs-frontend
    build: ./frontend
    environment:
      VUE_APP_MOCK: "false"
      VUE_APP_API_URL: "http://0.0.0.0:3000"
    ports:
      - "8080:80"
